name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: SSH and deploy go
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/lanjukang
            git pull origin main
            systemctl restart lanjukang
